OCAMLMAKEFILE = OCamlMakefile

RESULT = kmoy
SOURCES = vector.mli vector.ml mset.mli mset.ml listutils.mli listutils.ml kmoy.mli kmoy.ml
PACKS = graphics

all: native-code-library byte-code-library
install: libinstall
uninstall: libuninstall

include $(OCAMLMAKEFILE)
